/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef JOB_APPLICATION_PRIVATE_H
#define JOB_APPLICATION_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.0.1.2"
#define VER_MAJOR	2
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	2
#define COMPANY_NAME	""
#define FILE_VERSION	"2.0.1.2"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"2.0.1.2"

#endif /*JOB_APPLICATION_PRIVATE_H*/
