/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef JOB_APPLICATION_PRIVATE_H
#define JOB_APPLICATION_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"3.9.1.0"
#define VER_MAJOR	3
#define VER_MINOR	9
#define VER_RELEASE	1
#define VER_BUILD	0
#define COMPANY_NAME	"EOP CSC1100"
#define FILE_VERSION	"3.9.1.0"
#define FILE_DESCRIPTION	"Final Project"
#define INTERNAL_NAME	"IZZAT AMEIR"
#define LEGAL_COPYRIGHT	"Copyright (C) 2016 zamzameir"
#define LEGAL_TRADEMARKS	"2016"
#define ORIGINAL_FILENAME	"EXPRESS ENGINEERING SDN BHD"
#define PRODUCT_NAME	"JOB APPLICATION SYSTEM"
#define PRODUCT_VERSION	"3.9.1.0"

#endif /*JOB_APPLICATION_PRIVATE_H*/
