/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef JOB_APPLICATION_PRIVATE_H
#define JOB_APPLICATION_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.3.0.0"
#define VER_MAJOR	2
#define VER_MINOR	3
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"EXPRESS ENGINEERING SDN BHD"
#define FILE_VERSION	"2.3.0.0"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	"IZZAT AMEIR"
#define LEGAL_COPYRIGHT	"Copyright (C) 2016 zamzameir"
#define LEGAL_TRADEMARKS	"2016"
#define ORIGINAL_FILENAME	"FINAL PROJECT"
#define PRODUCT_NAME	"JOB APPLICATION SYSTEM"
#define PRODUCT_VERSION	"2.3.0.0"

#endif /*JOB_APPLICATION_PRIVATE_H*/
